### ISSUE TITLE
Some questions about the dataset which was provided.

### ISSUE THREAD

**Issue by Cherishnoobs** [XinyuXia97/UCMFH#1]
Is the provided dataset extracted by Clip or CNN/Bow?

**Comment by XinyuXia97** [comment]
The provided dataset was extracted using the CLIP model.

**Comment by Cherishnoobs** [comment]
OK, Thanks!

**Comment by RIU-13** [comment]
> The provided dataset was extracted using the CLIP model.

Which model is exactly used? VIT-32B?
