### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by Leng-Lin** [XinyuXia97/UCMFH#9]
Hello, sorry to bother you，
    I want to use your code with my datasets，the image is represented as a 4096 dimensional VGG vector and the text is represented as a 1,386 dimensional BoW vector，because the demension is not equal ，so when I try to use FuseTransEncoder，there is somethong wrong，I put the image and text into the FuseTransEncoder and  acquire the 4096 dimensional img_query and 1386 dimensional txt_query，due to the ContrastiveLoss need input from the same dimension，it can't be use.
    I try to ues linear layer to have the same dimension of img and txt  and put them into FuseTransEncoder，so that I can calculate loss1，but it cann't be uesful，the MAP value is too low，I want to know if you have some solution about my problem？
    Thank you for reading my question！

**Comment by XinyuXia97** [comment]
I think issue #6 will help you.

**Comment by Leng-Lin** [comment]
> I think issue #6 will help you.

thankyou, I have applied for permission at 14:15 pm，please agree
